#!/usr/bin/env bash

case "$1" in
	autoselect-monitor)
		if [ "$(xrandr | grep 'HDMI1 connected')" != "" ]; then
			# I want to disable my builtin monitor when I'm connected
			# to the external one.
			i3-tools select-monitor HDMI1
		else
			i3-tools select-monitor LVDS1
		fi
		;;
	select-monitor)
		if [ "$2" == "HDMI1" ]; then
			xrandr --output HDMI1 --auto --output LVDS1 --off
		elif [ "$2" == "--all" ]; then
			xrandr --output HDMI1 --auto --output LVDS1 --auto
		else
			xrandr --output HDMI1 --off --output LVDS1 --auto
		fi
		# Need to force refresh the wallpaper
		feh --bg-scale ~/Pictures/Desktop.jpg
		;;
	select-sound-card)
		if [[ "$(pacmd list-cards)" == *Focusrite* ]]; then
			# If my external sound card is connected I want to connect to it.
			for input in "$(pacmd list-sink-inputs | grep index | grep -Eo '[0-9]+$')"; do
				pacmd move-sink-input "$input" 0
			done
		fi
		;;
esac
